export default [
  {
    path: '/user',
    layout: false,
    routes: [
      {
        path: '/user',
        routes: [
          {
            name: 'login',
            path: '/user/login',
            component: './user/Login',
          },
        ],
      },
      {
        component: './404',
      },
    ],
  },
  {
    path: '/layout',
    name: '布局',
    icon: 'crown',
    routes: [
      {
        path: 'prolayout',
        name: '高级布局',
        icon: 'smile',
        routes: [
          {
            path: 'BasedOnUsing',
            name: '基本使用',
            icon: 'smile',
            component: './layout/prolayout/BasedOnUsing',
          },
          {
            path: 'LoadMenuFromTheServer',
            name: '从服务器加载 menu',
            icon: 'smile',
            component: './layout/prolayout/LoadMenuFromTheServer',
          },
          {
            path: 'LoadMenuFromTheServerAndIcon',
            name: '从服务器加载 menu 并且使用 icon',
            icon: 'smile',
            component: './layout/prolayout/LoadMenuFromTheServerAndIcon',
          },
          {
            path: 'CustomizeTheMenuContent',
            name: '自定义 menu 的内容',
            icon: 'smile',
            component: './layout/prolayout/CustomizeTheMenuContent',
          },
          {
            path: 'CustomFooter',
            name: '自定义页脚',
            icon: 'smile',
            component: './layout/prolayout/CustomFooter',
          },
          {
            path: 'SearchMenu',
            name: '搜索菜单',
            icon: 'smile',
            component: './layout/prolayout/SearchMenu',
          },
          {
            path: 'MultipleRoutesCorrespondToAMenuItem',
            name: '多个路由对应一个菜单项',
            icon: 'smile',
            component: './layout/prolayout/MultipleRoutesCorrespondToAMenuItem',
          },
          {
            path: 'AllMenusAreOpenedByDefault',
            name: '默认打开所有菜单',
            icon: 'smile',
            component: './layout/prolayout/AllMenusAreOpenedByDefault',
          },
          {
            path: 'UsingIconFont',
            name: '使用 IconFont',
            icon: 'smile',
            component: './layout/prolayout/UsingIconFont',
          },
          {
            path: 'GhostMode',
            name: 'ghost 模式',
            icon: 'smile',
            component: './layout/prolayout/GhostMode',
          },
          {
            path: 'NestedLayout',
            name: '嵌套布局',
            icon: 'smile',
            component: './layout/prolayout/NestedLayout',
          },
          {
            path: 'CustomizedCollapsed',
            name: '自定义的 collapsed',
            icon: 'smile',
            component: './layout/prolayout/CustomizedCollapsed',
          },
          {
            path: 'TheBreadCrumbsAreShownAtTheTop',
            name: '面包屑显示在顶部',
            icon: 'smile',
            component: './layout/prolayout/TheBreadCrumbsAreShownAtTheTop',
          },
          {
            path: 'MultiLevelSiteNavigation',
            name: '多级站点导航',
            icon: 'smile',
            component: './layout/prolayout/MultiLevelSiteNavigation',
          },
          {
            path: 'ImmersiveNavigation',
            name: '沉浸式导航',
            icon: 'smile',
            component: './layout/prolayout/ImmersiveNavigation',
          },
          {
            path: 'PreventBad',
            name: '防止白屏',
            icon: 'smile',
            component: './layout/prolayout/PreventBad',
          },
        ],
      },
      {
        path: 'pagecontainer',
        name: '页容器',
        icon: 'smile',
        routes: [
          {
            path: 'BasicUse',
            name: '基本使用',
            icon: 'smile',
            component: './layout/pagecontainer/BasicUse',
          },
          {
            path: 'FixedHeader',
            name: '固定表头',
            icon: 'smile',
            component: './layout/pagecontainer/FixedHeader',
          },
          {
            path: 'HideTheCrumbs',
            name: '隐藏面包屑',
            icon: 'smile',
            component: './layout/pagecontainer/HideTheCrumbs',
          },
          {
            path: 'PageLoading',
            name: '页面加载中',
            icon: 'smile',
            component: './layout/pagecontainer/PageLoading',
          },
        ],
      },
      {
        path: 'procard',
        name: '高级卡片',
        icon: 'smile',
        routes: [
          {
            path: 'BasedCard',
            name: '基础卡片',
            icon: 'smile',
            component: './layout/procard/BasedCard',
          },
          {
            path: 'GridLayout',
            name: '栅格布局',
            icon: 'smile',
            component: './layout/procard/GridLayout',
          },
          {
            path: 'Responsive',
            name: '响应式',
            icon: 'smile',
            component: './layout/procard/Responsive',
          },
          {
            path: 'CardSegmentation',
            name: '卡片切分',
            icon: 'smile',
            component: './layout/procard/CardSegmentation',
          },
          {
            path: 'LeftAndRightColumns',
            name: '左右分栏',
            icon: 'smile',
            component: './layout/procard/LeftAndRightColumns',
          },
          {
            path: 'ComplexSegmentation',
            name: '复杂切分',
            icon: 'smile',
            component: './layout/procard/ComplexSegmentation',
          },
          {
            path: 'GridSpacing',
            name: '栅格间隔',
            icon: 'smile',
            component: './layout/procard/GridSpacing',
          },
          {
            path: 'MoreLineCard',
            name: '多行卡片',
            icon: 'smile',
            component: './layout/procard/MoreLineCard',
          },
          {
            path: 'GroupShow',
            name: '分组展示',
            icon: 'smile',
            component: './layout/procard/GroupShow',
          },
          {
            path: 'TheTitleHasADividingLine',
            name: '标题带分割线',
            icon: 'smile',
            component: './layout/procard/TheTitleHasADividingLine',
          },
          {
            path: 'Folding',
            name: '可折叠',
            icon: 'smile',
            component: './layout/procard/Folding',
          },
          {
            path: 'DeckExpansion',
            name: '卡片组展开',
            icon: 'smile',
            component: './layout/procard/DeckExpansion',
          },
          {
            path: 'CenterContent',
            name: '内容居中',
            icon: 'smile',
            component: './layout/procard/CenterContent',
          },
          {
            path: 'Loading',
            name: '加载中',
            icon: 'smile',
            component: './layout/procard/Loading',
          },
          {
            path: 'ActionItems',
            name: '操作项',
            icon: 'smile',
            component: './layout/procard/ActionItems',
          },
          {
            path: 'NoTitle',
            name: '无标题',
            icon: 'smile',
            component: './layout/procard/NoTitle',
          },
          {
            path: 'WithBorders',
            name: '带边框',
            icon: 'smile',
            component: './layout/procard/WithBorders',
          },
          {
            path: 'ToTheEffect',
            name: '浮出效果',
            icon: 'smile',
            component: './layout/procard/ToTheEffect',
          },
          {
            path: 'Tab',
            name: '页签',
            icon: 'smile',
            component: './layout/procard/Tab',
          },
          {
            path: 'CardTab',
            name: '卡片式页签',
            icon: 'smile',
            component: './layout/procard/CardTab',
          },
          {
            path: 'InsideTheCard',
            name: '内部卡片',
            icon: 'smile',
            component: './layout/procard/InsideTheCard',
          },
          {
            path: 'ExampleVerticalSteps',
            name: '竖向步骤示例',
            icon: 'smile',
            component: './layout/procard/ExampleVerticalSteps',
          },
        ],
      },
      {
        path: 'watermark',
        name: '水印组件',
        icon: 'smile',
        routes: [
          {
            path: 'LeadTheWatermark',
            name: '前置水印',
            icon: 'smile',
            component: './layout/watermark/LeadTheWatermark',
          },
          {
            path: 'TextWatermarking',
            name: '文字水印',
            icon: 'smile',
            component: './layout/watermark/TextWatermarking',
          },
          {
            path: 'ImageWatermarking',
            name: '图片水印',
            icon: 'smile',
            component: './layout/watermark/ImageWatermarking',
          },
          {
            path: 'CustomConfiguration',
            name: '自定义配置',
            icon: 'smile',
            component: './layout/watermark/CustomConfiguration',
          },
        ],
      },
      {
        path: 'statisticcard',
        name: '指标卡',
        icon: 'smile',
        routes: [
          {
            path: 'BasicUse ',
            name: '基本使用',
            icon: 'smile',
            component: './layout/statisticcard/BasicUse',
          },
          {
            path: 'OnlyTheChart ',
            name: '只有图表',
            icon: 'smile',
            component: './layout/statisticcard/OnlyTheChart',
          },
          {
            path: 'AdditionalIndicators ',
            name: '额外指标',
            icon: 'smile',
            component: './layout/statisticcard/AdditionalIndicators',
          },
          {
            path: 'PrimaryAndSecondaryRelations ',
            name: '总分/主次关系',
            icon: 'smile',
            component: './layout/statisticcard/PrimaryAndSecondaryRelations',
          },
          {
            path: 'PerformanceTargets ',
            name: '总分/业绩目标',
            icon: 'smile',
            component: './layout/statisticcard/PerformanceTargets',
          },
          {
            path: 'GroupIndicators ',
            name: '分组指标',
            icon: 'smile',
            component: './layout/statisticcard/GroupIndicators',
          },
          {
            path: 'GroupIndicatorsWithCharts ',
            name: '分组指标带图表',
            icon: 'smile',
            component: './layout/statisticcard/GroupIndicatorsWithCharts',
          },
          {
            path: 'FormulaCalculationIndex ',
            name: '公式计算指标',
            icon: 'smile',
            component: './layout/statisticcard/FormulaCalculationIndex',
          },
          {
            path: 'StateDisplay ',
            name: '状态展示',
            icon: 'smile',
            component: './layout/statisticcard/StateDisplay',
          },
          {
            path: 'IconToShow ',
            name: '图标展示',
            icon: 'smile',
            component: './layout/statisticcard/IconToShow',
          },
          {
            path: 'CardLayout ',
            name: '卡片布局',
            icon: 'smile',
            component: './layout/statisticcard/CardLayout',
          },
          {
            path: 'TheChartOnTheRightOrLeft ',
            name: '图表在右或左',
            icon: 'smile',
            component: './layout/statisticcard/TheChartOnTheRightOrLeft',
          },
          {
            path: 'IndicatorTabLinkage ',
            name: '指标页签联动',
            icon: 'smile',
            component: './layout/statisticcard/IndicatorTabLinkage',
          },
          {
            path: 'SequentialTrend ',
            name: '环比趋势',
            icon: 'smile',
            component: './layout/statisticcard/SequentialTrend',
          },
        ],
      },
      {
        path: 'checkcard',
        name: '多选卡片',
        icon: 'smile',
        routes: [
          {
            path: 'BasicUse',
            name: '基本使用',
            icon: 'smile',
            component: './layout/checkcard/BasicUse',
          },
          {
            path: 'RadioMode',
            name: '单选模式',
            icon: 'smile',
            component: './layout/checkcard/RadioMode',
          },
          {
            path: 'MultiselectMode',
            name: '多选模式',
            icon: 'smile',
            component: './layout/checkcard/MultiselectMode',
          },
          {
            path: 'DifferentSizes',
            name: '不同尺寸',
            icon: 'smile',
            component: './layout/checkcard/DifferentSizes',
          },
          {
            path: 'CustomSize',
            name: '自定义尺寸',
            icon: 'smile',
            component: './layout/checkcard/CustomSize',
          },
          {
            path: 'UseInForms',
            name: '表单中使用',
            icon: 'smile',
            component: './layout/checkcard/UseInForms',
          },
          {
            path: 'CombinationStyle',
            name: '组合样式',
            icon: 'smile',
            component: './layout/checkcard/CombinationStyle',
          },
          {
            path: 'CustomProfilePicture',
            name: '自定义头像',
            icon: 'smile',
            component: './layout/checkcard/CustomProfilePicture',
          },
          {
            path: 'CustomTitle',
            name: '自定义标题',
            icon: 'smile',
            component: './layout/checkcard/CustomTitle',
          },
          {
            path: 'CustomDescription',
            name: '自定义描述',
            icon: 'smile',
            component: './layout/checkcard/CustomDescription',
          },
          {
            path: 'DefaultChecked',
            name: '默认选中',
            icon: 'smile',
            component: './layout/checkcard/DefaultChecked',
          },
          {
            path: 'ActionBar',
            name: '操作栏',
            icon: 'smile',
            component: './layout/checkcard/ActionBar',
          },
          {
            path: 'ComponentLoading',
            name: '组件 Loading',
            icon: 'smile',
            component: './layout/checkcard/ComponentLoading',
          },
          {
            path: 'PureImageOptions',
            name: '纯图片选项',
            icon: 'smile',
            component: './layout/checkcard/PureImageOptions',
          },
          {
            path: 'OptionNotAvailable',
            name: '选项不可用',
            icon: 'smile',
            component: './layout/checkcard/OptionNotAvailable',
          },
          {
            path: 'OptionList',
            name: '选项列表',
            icon: 'smile',
            component: './layout/checkcard/OptionList',
          },
          {
            path: 'ApplicationListExample',
            name: '应用列表示例',
            icon: 'smile',
            component: './layout/checkcard/ApplicationListExample',
          },
          {
            path: 'Layout',
            name: '布局',
            icon: 'smile',
            component: './layout/checkcard/Layout',
          },
        ],
      },
      {
        component: './404',
      },
    ],
  },
  {
    path: '/dataentry',
    name: '数据录入',
    icon: 'crown',
    routes: [
      {
        path: 'proform',
        name: '高级表单',
        icon: 'smile',
        routes: [
          {
            path: 'BasicUse',
            name: '基本使用',
            icon: 'smile',
            component: './dataentry/proform/BasicUse',
          },
          {
            path: 'LabelAndFormItemLayout',
            name: '标签与表单项布局',
            icon: 'smile',
            component: './dataentry/proform/LabelAndFormItemLayout',
          },
        ],
      },

      {
        component: './404',
      },
    ],
  },
  {
    path: '/',
    redirect: '/layout/prolayout/BasedOnUsing',
  },
  {
    component: './404',
  },
];
